name: Fly Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group  # 同時に複数のデプロイが行われないように制御
    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      # キャッシュの設定
      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # https://fly.io/docs/launch/continuous-deployment-with-github-actions/
      - uses: superfly/flyctl-actions/setup-flyctl@master
        name: Setup Flyctl

      - name: Deploy to Fly.io
        run: |
          cd backend
          flyctl deploy --remote-only -a backend-summer-feather-3833
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
